'''
Phase classification using fitted peak parameters for Titanium Oxide Transformation
All qualification logic together (Combined and Option 1, 5, 6) without prompt.
Labels scans "before" or "after" heating 
Trains classifer to predict "phase" Rutile or Anatase 
'''

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from scipy.optimize import curve_fit

# Gaussian fit function for peaks
def gaussian(x, a, x0, sigma):
    return a * np.exp(-(x - x0)**2 / (2 * sigma**2))

# Import and run all scanning strategies
# Option: Manual choose which but for now auto selection
def run_all_qualifications():
    from auto1_subset_peaks import main as run_subset_peaks
    from auto5_shifted_peaks import main as run_shifted_peaks
    from auto6_regions_change import main as run_change_regions

    print("Running Option 1: Subset Peaks")
    run_subset_peaks()

    print("Running Option 5: Shifted Peaks")
    run_shifted_peaks()

    print("Running Option 6: Change Regions")
    run_change_regions()

# Phase Classification 
def classify_phase_change(fitted_csv):
    df = pd.read_csv(fitted_csv)
    results = []
    for _, row in df.iterrows():
        label = "Stable"
        if abs(row.get("shift", 0)) > 0.2:
            label = "Phase Shift"
        elif row.get("fitted_sigma", 0) > 0.15:
            label = "Growth"
        elif row.get("fitted_sigma", 0) < 0.05:
            label = "Shrink"
        results.append({**row, "phase_class": label})
    result_df = pd.DataFrame(results)
    result_df.to_csv("classified_peaks.csv", index=False) # for machine learning later
    print("\nPhase classification saved to 'classified_peaks.csv'.")


# Train classifier to predict phase (Anatase vs Rutile)
def train_phase_classifier(fitted_csv):
    df = pd.read_csv(fitted_csv)

    # Assign heating condition
    HEATING_THRESHOLD = 820  #°C for TiO2 phase transition
    if "ctemp" in df.columns:
        df["condition"] = df["ctemp"].apply(lambda t: "before" if t < HEATING_THRESHOLD else "after")
    else:
        df["condition"] = "unknown"

    # Placeholder: Label phase by scan number
    df["phase"] = df["scan"].apply(lambda s: "Anatase" if s < 66 else "Rutile")

    features = df[["fitted_center", "fitted_sigma", "shift", "intensity"]]
    labels = df["phase"]

    X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.3, random_state=42)
    model = RandomForestClassifier(n_estimators=100, random_state=42)
    model.fit(X_train, y_train)

    print("\nPhase prediction report:")
    print(classification_report(y_test, model.predict(X_test)))

    df["predicted_phase"] = model.predict(features)
    df.to_csv("labeled_peaks_by_phase.csv", index=False)

    # Plot predicted phase count over scan index
    plt.figure(figsize=(10, 5))
    counts = df.groupby(["scan", "predicted_phase"]).size().unstack(fill_value=0)
    for phase in counts.columns:
        plt.plot(counts.index, counts[phase], label=phase, marker='o')
    plt.title("Predicted Phase Over Scan Index")
    plt.xlabel("Scan Number")
    plt.ylabel("Peak Count")
    plt.legend(title="Predicted Phase")
    plt.grid(True)
    plt.tight_layout()
    plt.show()

def main():
    print("Executing all options using smart combined logic...")
    run_all_qualifications()

    # Perform classification on fitted peaks (if generated by Option 5)
    fitted_csv = "fitted_peaks_shifted.csv"
    if os.path.exists(fitted_csv):
        classify_phase_change(fitted_csv)
        train_phase_classifier(fitted_csv)
    print("Combined scan logic and classification complete.")

if __name__ == "__main__":
    main()